rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - ci / unit-tests (1.11)
      - ci / unit-tests (1.12)
      - ci / unit-tests (1.13)
      - ci / unit-tests (1.14)
      - ci / unit-tests (1.15)
      - ci / unit-tests (1.16)
      - ci / lint
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi-go
    permission: push
  - team: actools-go
    permission: push
