rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - ci / unit-tests (1.11) (pull_request)
      - ci / unit-tests (1.12) (pull_request)
      - ci / unit-tests (1.13) (pull_request)
      - ci / unit-tests (1.14) (pull_request)
      - ci / unit-tests (1.15) (pull_request)
      - ci / unit-tests (1.16) (pull_request)
      - ci / lint (pull_request)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi-go
    permission: push
  - team: actools-go
    permission: push
