---
name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - "1.11"
          - "1.12"
          - "1.13"
          - "1.14"
          - "1.15"
          - "1.16"
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
      - uses: actions/checkout@v4
      - run: go test -p 1 ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.16
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
